/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Area': { kind: 'OBJECT'; name: 'Area'; fields: { 'climbs': { name: 'climbs'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Climb'; ofType: null; }; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'parentArea': { name: 'parentArea'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'rockTypes': { name: 'rockTypes'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AreaToRockType'; ofType: null; }; }; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'topos': { name: 'topos'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Topo'; ofType: null; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'AreaToRockType': { kind: 'OBJECT'; name: 'AreaToRockType'; fields: { 'area': { name: 'area'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'rockType': { name: 'rockType'; type: { kind: 'OBJECT'; name: 'RockType'; ofType: null; } }; }; };
    'Boolean': unknown;
    'Climb': { kind: 'OBJECT'; name: 'Climb'; fields: { 'area': { name: 'area'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'climbType': { name: 'climbType'; type: { kind: 'OBJECT'; name: 'ClimbType'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'fa': { name: 'fa'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'gear': { name: 'gear'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'grade': { name: 'grade'; type: { kind: 'OBJECT'; name: 'Grade'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'pitches': { name: 'pitches'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Pitch'; ofType: null; }; }; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'ClimbType': { kind: 'OBJECT'; name: 'ClimbType'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'ENUM'; name: 'ClimbTypeNameRef'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'ClimbTypeNameRef': { name: 'ClimbTypeNameRef'; enumValues: 'boulder' | 'mixed' | 'sport' | 'trad'; };
    'CountriesFilterInput': { kind: 'INPUT_OBJECT'; name: 'CountriesFilterInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'Country': { kind: 'OBJECT'; name: 'Country'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'states': { name: 'states'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'State'; ofType: null; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'DateTime': unknown;
    'Grade': { kind: 'OBJECT'; name: 'Grade'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'gradeSystem': { name: 'gradeSystem'; type: { kind: 'OBJECT'; name: 'GradeSystem'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'maxScore': { name: 'maxScore'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'minScore': { name: 'minScore'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'GradeSystem': { kind: 'OBJECT'; name: 'GradeSystem'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'shortName': { name: 'shortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'Guide': { kind: 'OBJECT'; name: 'Guide'; fields: { 'areas': { name: 'areas'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Area'; ofType: null; }; }; } }; 'country': { name: 'country'; type: { kind: 'OBJECT'; name: 'Country'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'gradeSystems': { name: 'gradeSystems'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GuideToGradeSystem'; ofType: null; }; }; } }; 'heightSystem': { name: 'heightSystem'; type: { kind: 'OBJECT'; name: 'HeightSystem'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'notices': { name: 'notices'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Notice'; ofType: null; }; }; } }; 'slug': { name: 'slug'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'state': { name: 'state'; type: { kind: 'OBJECT'; name: 'State'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'visibility': { name: 'visibility'; type: { kind: 'ENUM'; name: 'VisibilityRef'; ofType: null; } }; }; };
    'GuideFilterInput': { kind: 'INPUT_OBJECT'; name: 'GuideFilterInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'GuideToGradeSystem': { kind: 'OBJECT'; name: 'GuideToGradeSystem'; fields: { 'gradeSystem': { name: 'gradeSystem'; type: { kind: 'OBJECT'; name: 'GradeSystem'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; }; };
    'HeightSystem': { kind: 'OBJECT'; name: 'HeightSystem'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'ENUM'; name: 'HeightSystemNameRef'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'HeightSystemNameRef': { name: 'HeightSystemNameRef'; enumValues: 'ft' | 'm'; };
    'ID': unknown;
    'Int': unknown;
    'Media': { kind: 'OBJECT'; name: 'Media'; fields: { 'alt': { name: 'alt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'area': { name: 'area'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'climb': { name: 'climb'; type: { kind: 'OBJECT'; name: 'Climb'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'width': { name: 'width'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'addGuide': { name: 'addGuide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'deleteGuide': { name: 'deleteGuide'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'updateGuide': { name: 'updateGuide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; }; };
    'Notice': { kind: 'OBJECT'; name: 'Notice'; fields: { 'area': { name: 'area'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'climb': { name: 'climb'; type: { kind: 'OBJECT'; name: 'Climb'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'summary': { name: 'summary'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'Pitch': { kind: 'OBJECT'; name: 'Pitch'; fields: { 'climb': { name: 'climb'; type: { kind: 'OBJECT'; name: 'Climb'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'grade': { name: 'grade'; type: { kind: 'OBJECT'; name: 'Grade'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'countries': { name: 'countries'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Country'; ofType: null; }; }; } }; 'country': { name: 'country'; type: { kind: 'OBJECT'; name: 'Country'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'guides': { name: 'guides'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Guide'; ofType: null; }; }; } }; }; };
    'RockType': { kind: 'OBJECT'; name: 'RockType'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'State': { kind: 'OBJECT'; name: 'State'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'String': unknown;
    'Topo': { kind: 'OBJECT'; name: 'Topo'; fields: { 'area': { name: 'area'; type: { kind: 'OBJECT'; name: 'Area'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'guide': { name: 'guide'; type: { kind: 'OBJECT'; name: 'Guide'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'media': { name: 'media'; type: { kind: 'OBJECT'; name: 'Media'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'VisibilityRef': { name: 'VisibilityRef'; enumValues: 'private' | 'public'; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}